name: taniv4
description: A new Flutter project.
pversion: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


enublish_to: 'none'
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^2.1.0
  file_picker: ^3.0.1

  flutter_image_compress: ^1.1.1
 
  uuid: ^3.0.4 
  curved_navigation_bar: ^1.0.3
  # UI KIT Packages
  flutter_rating_bar: ^4.0.0
  flutter_colorpicker: ^1.0.3
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  geolocator: ^8.0.3
  permission_handler: ^8.3.0
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  carousel_slider: ^4.1.1
  badges:
  flutter_custom_clippers:
  material_design_icons_flutter: ^5.0.6996
  blur: ^3.1.0
  rubber:
  sliding_up_panel:
  flutter_svg:
  provider: ^6.0.3
  http: ^0.13.3
  google_sign_in: ^5.4.1
  

  #objectdetections

  tflite: ^1.1.2
  tflite_flutter: ^0.9.0
  image_picker: ^0.8.4+11
  camera: ^0.9.4+5
  meta: ^1.1.8
  video_player: ^2.1.14
  path_provider: ^2.0.2

  
  
  

  # FIREBASE
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore:  

  # STATE MANAGEMENT
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audio/
    - assets/document/
    - assets/font/
    - assets/image/
    - assets/video/
    - assets/tflite/

